	set(VER 4.11)
	set(RC .0-rc3)
  set(RTEMS_INSTALL_DIR $ENV{RTEMS_INSTALL_DIR} CACHE PATH "path to rtems installation dir" FORCE)
	set(RTEMS_CC_PREFIX $ENV{TARGET}${VER})
  set(RTEMS_VER_PATH ${VER}${RC}/$ENV{TARGET}${VER})
  set(INSTALL_PREFIX $ENV{INSTALL_PREFIX})
  set(BSP $ENV{BSP})


  if(EXISTS ${RTEMS_INSTALL_DIR}/${RTEMS_VER_PATH}/${BSP}/lib/include/rtems/system.h)
    message("-- Looking for RTEMS - found in ${RTEMS_INSTALL_DIR}")
    set(RTEMS_FOUND TRUE)
    set(RTEMS_INCLUDE_DIRS ${RTEMS_INSTALL_DIR}/${RTEMS_VER_PATH}/${BSP}/lib/include )
    set(RTEMS_LIBRARIES -L${RTEMS_INSTALL_DIR}/${RTEMS_VER_PATH}/${BSP}/lib -lrtemsbsp -lrtemscpu -lc )

    set(RTEMS_BUILD ${INSTALL_PREFIX}/rtems/${RTEMS_VER_PATH})
    set(RTEMS_INSTALL_POINT ${INSTALL_PREFIX}/rtems/${VER}${RC})
    set(RTEMS_INSTALL_DIR ${RTEMS_INSTALL_POINT})
    set(PROJECT_RELEASE ${RTEMS_BUILD}/${BSP})
    set(PROJECT_TOOLS ${RTEMS_BUILD}/${BSP}/build-tools)
    set(CMAKE_C_COMPILER ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-gcc)
    set(AS ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-as)
    set(AR ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-ar)
    set(NM ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-nm)
    set(LD ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-ld)
    set(SIZE ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-size)
    set(OBJCOPY ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-objcopy)
    set(RANLIB ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-ranlib)
    set(CMAKE_CXX_COMPILER ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-g++)
    set(CXXLINK ${RTEMS_INSTALL_POINT}/bin/${RTEMS_CC_PREFIX}-g++)
    set(ARFLAGS "-ruv")
    set(CDEFS "-D__RTEMS__")
    set(BUILD_STATIC ON)
    set(NOT_BUILD_SHARED ON)

    set(CFLAGS "--pipe -DBOOST_SYSTEM_NO_DEPRECATED  -D__BSD_VISIBLE  -D__RTEMS__  -DBoost_USE_STATIC_LIBS  -DBOOST_THREAD_POSIX  -DNOT_BUILD_SHARED -DRUBY_EXTENSIONS_AVAILABLE=NO -B${RTEMS_BUILD}/${BSP}/lib/ -specs bsp_specs -qrtems ${IMPORT_CPPFLAGS}  ${DIR_CPPFLAGS} -I${RTEMS_BUILD}/${BSP}/lib/include  -I${RTEMS_BUILD}/include  -I${RTEMS_BUILD}/${BSP}/lib/include/networking  -I${RTEMS_BUILD}/${BSP}/lib/include/sys  -I${INSTALL_PREFIX}/omniORB/include  -I${INSTALL_PREFIX}/boost/include ")

    if ("${RTEMS_CC_PREFIX}" MATCHES "i?86-*")
	set (CFLAGS "${CFLAGS} -D__i386__ -march=i486  -Wl,-Ttext,0x00100000")
    elseif("${RTEMS_CC_PREFIX}" MATCHES "sparc-*")
	set (CFLAGS "${CFLAGS} -D__SPARC__")
    endif()

    set(CXXFLAGS "${CFLAGS} -fexceptions -fpermissive")

    set(CMAKE_C_FLAGS ${CFLAGS})
    set(CMAKE_CXX_FLAGS ${CXXFLAGS})

  else(EXISTS ${RTEMS_INSTALL_DIR}/${RTEMS_VER_PATH}/${BSP}/lib/include/rtems/system.h)
    message(FATAL_ERROR "-- Looking for RTEMS - not found (tried: ${RTEMS_INSTALL_DIR}/${RTEMS_VER_PATH}/${BSP}/lib/include/rtems/system.h)")
    set(RTEMS_FOUND FALSE)
  endif(EXISTS ${RTEMS_INSTALL_DIR}/${RTEMS_VER_PATH}/${BSP}/lib/include/rtems/system.h)
